version: "3.2"

services:
  dev:
    container_name: aow
    image: paritytech/ci-linux:production
    working_dir: /var/www/aow
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/aow/.cargo
    volumes:
      - .:/var/www/aow
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/aow --dev --ws-external"
